<?php

/**
 * Implementation of hook_ctools_plugin_api().
 */
function googlemapstyled_ctools_plugin_api($module, $api) {
  if ($module == "openlayers") {
    switch ($api) {
      case 'openlayers_layers':
        return array('version' => 1);
      case 'openlayers_styles':
        return array('version' => 1);
    }
  }
}




/**
 * Implementation of openlayers_layer_type
 */
function googlemapstyled_openlayers_layer_types() {
  return array(
    'openlayers_layer_type_googlemapstyled' => array(
      'title' => t('Custom google map layer'),
      'description' => t('Custom Google map layer using Google Maps API Styled Map Wizard'),
       'layer_type' => array(
        'path' => drupal_get_path('module', 'googlemapstyled') . '/includes/layer_types',
        'file' => 'googlemapstyled.inc',
        'class' => 'openlayers_layer_type_googlemapstyled',
        'parent' => 'openlayers_layer_type',
      ),
    ),
  );
}
